CREATE TABLE currency (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    abbreviation VARCHAR(10) UNIQUE NOT NULL,
    value NUMERIC(30, 8) NOT NULL,
    capitalisation NUMERIC(19,2) NOT NULL,
    activated BOOLEAN NOT NULL,
    image BYTEA,
    time TIMESTAMP
);