CREATE TYPE USER_STATE AS ENUM ('ACTIVE', 'FROZEN', 'DELETED');
CREATE TYPE USER_STATUS AS ENUM ('BASIC', 'PREMIUM', 'GOLD');

CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL ,
    password VARCHAR(300) NOT NULL,
    state USER_STATE NOT NULL,
    status USER_STATUS NOT NULL
);